from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="campus_admin_dashboard"),
    path("students/", views.students, name="campus_admin_students"),
    path(
        "students/<int:student_id>/",
        views.student_view,
        name="campus_admin_student_view",
    ),
    path(
        "students/<int:student_id>/edit/",
        views.edit_student,
        name="campus_admin_edit_student",
    ),
    path(
        "students/<int:student_id>/pfp/delete/",
        views.delete_student_profile_picture,
        name="campus_admin_delete_student_pfp",
    ),
    path(
        "students/<int:student_id>/message/",
        views.send_message,
        name="campus_admin_send_message",
    ),
    path(
        "students/<int:student_id>/suspend/",
        views.suspend_student,
        name="campus_admin_suspend_student",
    ),
    path(
        "students/<int:student_id>/unsuspend/",
        views.unsuspend_student,
        name="campus_admin_unsuspend_student",
    ),
    path(
        "students/<int:student_id>/delete/",
        views.delete_student,
        name="campus_admin_delete_student",
    ),
    path(
        "students/<int:student_id>/message/<int:message_id>/delete/",
        views.delete_message,
        name="campus_admin_delete_message",
    ),
    path("clans/", views.clans, name="campus_admin_clans"),
    path("clans/<int:clan_id>/", views.clan_view, name="campus_admin_clan_view"),
    path("clans/<int:clan_id>/edit/", views.edit_clan, name="campus_admin_edit_clan"),
    path(
        "clans/<int:clan_id>/suspend/",
        views.suspend_clan,
        name="campus_admin_suspend_clan",
    ),
    path(
        "clans/<int:clan_id>/unsuspend/",
        views.unsuspend_clan,
        name="campus_admin_unsuspend_clan",
    ),
    path(
        "clans/<int:clan_id>/delete/",
        views.delete_clan,
        name="campus_admin_delete_clan",
    ),
    path(
        "clans/<int:clan_id>/message/",
        views.message_clan,
        name="campus_admin_message_clan",
    ),
    path(
        "clans/<int:clan_id>/members/<int:member_id>/remove/",
        views.remove_clan_member,
        name="campus_admin_remove_clan_member",
    ),
    path(
        "clans/<int:clan_id>/posts/<int:post_id>/edit/",
        views.edit_clan_post_admin,
        name="campus_admin_edit_clan_post",
    ),
    path(
        "clans/<int:clan_id>/posts/<int:post_id>/delete/",
        views.delete_clan_post_admin,
        name="campus_admin_delete_clan_post",
    ),
    path(
        "clans/<int:clan_id>/stories/<int:story_id>/delete/",
        views.delete_clan_story_admin,
        name="campus_admin_delete_clan_story",
    ),
    path(
        "clans/<int:clan_id>/projects/create/",
        views.clan_project_manage,
        name="campus_admin_create_clan_project",
    ),
    path(
        "clans/<int:clan_id>/projects/<int:project_id>/edit/",
        views.clan_project_manage,
        name="campus_admin_edit_clan_project",
    ),
    path(
        "clans/<int:clan_id>/projects/<int:project_id>/delete/",
        views.delete_clan_project,
        name="campus_admin_delete_clan_project",
    ),
    path(
        "clans/<int:clan_id>/recruitments/create/",
        views.clan_recruitment_manage,
        name="campus_admin_create_clan_recruitment",
    ),
    path(
        "clans/<int:clan_id>/recruitments/<int:recruitment_id>/edit/",
        views.clan_recruitment_manage,
        name="campus_admin_edit_clan_recruitment",
    ),
    path(
        "clans/<int:clan_id>/recruitments/<int:recruitment_id>/delete/",
        views.delete_clan_recruitment,
        name="campus_admin_delete_clan_recruitment",
    ),
    path("events/", views.events, name="campus_admin_events"),
    path("events/create/", views.create_event, name="campus_admin_create_event"),
    path(
        "events/<int:event_id>/edit/", views.edit_event, name="campus_admin_edit_event"
    ),
    path(
        "events/<int:event_id>/applications/",
        views.event_applications,
        name="campus_admin_event_applications",
    ),
    path(
        "events/<int:event_id>/trophies/",
        views.manage_event_trophy,
        name="campus_admin_manage_event_trophies",
    ),
    path(
        "events/<int:event_id>/trophies/<int:trophy_id>/delete/",
        views.delete_event_trophy,
        name="campus_admin_delete_event_trophy",
    ),
    path(
        "events/<int:event_id>/delete/",
        views.delete_event,
        name="campus_admin_delete_event",
    ),
    path("reports/", views.reports, name="campus_admin_reports"),
    path(
        "reports/monthly.csv",
        views.monthly_report_csv,
        name="campus_admin_monthly_report_csv",
    ),
    path(
        "reports/monthly.xlsx",
        views.monthly_report_excel,
        name="campus_admin_monthly_report_excel",
    ),
    path(
        "reports/monthly.pdf",
        views.monthly_report_pdf,
        name="campus_admin_monthly_report_pdf",
    ),
    path(
        "reports/monthly.json",
        views.monthly_report_json,
        name="campus_admin_monthly_report_json",
    ),
]
