# Generated by Django 6.1.1 on 2026-10-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedClanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('original_created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedStudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=150)),
                ('original_created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('participant_type', models.CharField(choices=[('clan', 'Clan'), ('student', 'Student'), ('both', 'Both')], default='clan', max_length=10)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_events/')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='campus_clans.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClanAdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='campus_clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_clans.clan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_clans.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_admin_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campus_clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions', to='campus_clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanEventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('participated', models.BooleanField(default=False)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_applications', to='campus_clans.clan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campus_admin.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campus_events/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campus_admin.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('clan', 'Clan'), ('student', 'Student')], default='clan', max_length=10)),
                ('participated_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='campus_clans.clan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='campus_admin.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='campus_clans.studentprofile')),
            ],
            options={
                'ordering': ['-participated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventClanParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_clan_participations', to='campus_clans.studentprofile')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_members', to='campus_admin.eventparticipation')),
            ],
            options={
                'ordering': ['selected_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_trophies', to='campus_clans.clan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='campus_admin.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_trophies', to='campus_clans.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions', to='campus_clans.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('clan__isnull', False)), fields=('event', 'clan'), name='unique_event_clan_participation'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('event', 'student'), name='unique_event_student_participation'),
        ),
        migrations.AddConstraint(
            model_name='eventclanparticipant',
            constraint=models.UniqueConstraint(fields=('participation', 'student'), name='unique_event_clan_selected_member'),
        ),
        migrations.AddConstraint(
            model_name='eventtrophy',
            constraint=models.UniqueConstraint(fields=('event', 'clan', 'award_name'), name='unique_event_clan_award'),
        ),
        migrations.AddConstraint(
            model_name='eventtrophy',
            constraint=models.UniqueConstraint(fields=('event', 'student', 'award_name'), name='unique_event_student_award'),
        ),
    ]
