# Generated by Django 6.1.1 on 2026-09-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0002_skilltype_studentprofile_about_studentprofile_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clan_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='clan_banners/')),
                ('speciality', models.CharField(max_length=150)),
                ('profile_description', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_clan', to='campus_clans.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campus_clans.clan')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clan_membership', to='campus_clans.studentprofile')),
            ],
        ),
    ]
