# Generated by Django 6.1.1 on 2026-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0003_clan_clanmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('co_leader', 'Co-Leader'), ('leader', 'Leader')], default='member', max_length=20),
        ),
    ]
