# Generated by Django 6.1.1 on 2026-09-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0004_clanmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='campus_clans.clan')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_clan_invitations', to='campus_clans.studentprofile')),
                ('invited_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_invitations', to='campus_clans.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('clan', 'invited_student'), name='unique_pending_clan_invitation')],
            },
        ),
    ]
