# Generated by Django 6.1.1 on 2026-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0005_claninvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claninvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
