# Generated by Django 6.1.1 on 2026-09-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0006_alter_claninvitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='campus_clans.clan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_join_requests', to='campus_clans.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('clan', 'student'), name='unique_pending_clan_join_request')],
            },
        ),
    ]
