# Generated by Django 6.1.1 on 2026-09-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0007_clanjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clan_posts/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_posts', to='campus_clans.studentprofile')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campus_clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clan_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_stories', to='campus_clans.studentprofile')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='campus_clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='ClanPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='campus_clans.clanpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_clan_posts', to='campus_clans.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'student'), name='unique_clan_post_like')],
            },
        ),
        migrations.CreateModel(
            name='ClanStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='campus_clans.clanstory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_clan_stories', to='campus_clans.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('story', 'student'), name='unique_clan_story_view')],
            },
        ),
    ]
