# Generated by Django 6.1.1 on 2026-09-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0008_clanpost_clanstory_clanpostlike_clanstoryview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clanstoryview',
            name='unique_clan_story_view',
        ),
        migrations.RenameField(
            model_name='clanstory',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='clanstory',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='clanstory',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clanpost',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clanpostlike',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_post_likes', to='campus_clans.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='clanstoryview',
            constraint=models.UniqueConstraint(fields=('story', 'student'), name='unique_story_viewer'),
        ),
    ]
