# Generated by Django 6.1.1 on 2026-09-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0009_remove_clanstoryview_unique_clan_story_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanjoinrequest',
            name='request_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('global', 'Global Recruitment')], default='direct', max_length=20),
        ),
        migrations.CreateModel(
            name='ClanRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='campus_clans.clan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clan_recruitments', to='campus_clans.studentprofile')),
                ('fields', models.ManyToManyField(blank=True, related_name='clan_recruitments', to='campus_clans.skilltype')),
            ],
        ),
        migrations.AddField(
            model_name='clanjoinrequest',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='campus_clans.clanrecruitment'),
        ),
        migrations.CreateModel(
            name='ClanRecruitmentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='campus_clans.clanrecruitment')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_recruitment_skills', to='campus_clans.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recruitment', 'skill'), name='unique_recruitment_skill')],
            },
        ),
    ]
