# Generated by Django 6.1.1 on 2026-09-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0010_clanjoinrequest_request_type_clanrecruitment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='clanmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'leader')), fields=('clan',), name='one_leader_per_clan'),
        ),
        migrations.AddConstraint(
            model_name='clanmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'co_leader')), fields=('clan',), name='one_co_leader_per_clan'),
        ),
        migrations.AddField(
            model_name='clanleaverequest',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='campus_clans.clan'),
        ),
        migrations.AddField(
            model_name='clanleaverequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_leave_requests', to='campus_clans.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='clanleaverequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('clan', 'student'), name='unique_pending_clan_leave_request'),
        ),
    ]
