# Generated by Django 6.1.1 on 2026-09-28 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_clans', '0011_clanleaverequest_clanmember_one_leader_per_clan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClanRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clan_recruitment_request', to='campus_clans.studentprofile')),
            ],
        ),
    ]
